### ISSUE TITLE
Does Algernon-Launcher work on SqueakNOS?

### ISSUE THREAD

**Issue by ghost** [HPI-SWA-Teaching/SWT16-Project-06#284]
Hi all. I wonder if Algernon-Launcher work on SqueakNOS. 

*SqueakNOS is an operating system written in squeak*.  So... does Algernon-Launcher work on SqueakNOS?

**Comment by LinqLover** [comment]
Hi, can you provide any details on squeak-os? Are you referring to [this one](https://marcusdenker.de/Squeak/SqueakOS/)? I have not yet tried it, but Algernon runs on Squeak 5.3 and newer and does not access the OS around the VM to my knowledge, so if SqueakOS implemented all VM capabilities and provided a 5.3+ image, it should work ...

**Comment by ghost** [comment]
Hi LinqLover.

> Hi, can you provide any details on squeak-os? 

I spelled it wrong, it wasn't squeak-os it was SqueakNOS... *"Squeak is an open, highly-portable Smalltalk-80 implementation, it runs on almost every operating system, and in bare hardware. What we gonna do with SqueakNOS is getting rid of the OS under Squeak, and we'll implement all the functionality in Smalltalk. - links: [squeak](https://wiki.squeak.org/squeak/1762), [squeaknos/sourceforge](squeaknos.sourceforge.net) and [squeaknos/blogspot](http://squeaknos.blogspot.com/)".*"

#### SqueakNOS screenshot
<img src="https://lh3.googleusercontent.com/-OMEP5mpaTXA/TYd_NqCtmPI/AAAAAAAABtU/dz9stJGpdDo/s1600/screenshot2.png" width="780px"/>

**source:** [squeaknos/sourceforge](https://sourceforge.net/projects/squeaknos/files/SqueakNOS/) 

> Are you referring to [this one](https://marcusdenker.de/Squeak/SqueakOS/)? 

No... SqueakNOS.

> I have not yet tried it, but Algernon runs on Squeak 5.3 and newer and does not access the OS around the VM to my knowledge, 

I have a virtual machine... and would like to know how can I check the Squeak version to see if it is 5.3 and newer in SqueakNOS?

> so if SqueakOS implemented all VM capabilities and provided a 5.3+ image, it should work ...

So... thanks for all the information.

**Comment by LinqLover** [comment]
Thanks for the links! Sounds very exciting, but unfortunately, development seems to have ended over ten years ago? I doubt it will work with Squeak 5.3, but you can give it a try anyway ...

Usually, you can find out your Squeak version from "About Squeak" at the beginning of the docking bar:

![image](https://user-images.githubusercontent.com/38782922/190378015-76e67dce-648a-4294-95bc-cb6212d7f4d3.png)
![image](https://user-images.githubusercontent.com/38782922/190378135-89ed059c-3f07-4cf8-976a-2d662cf8d613.png)

If the docking bar is not available, you can evaluate `Smalltalk version` anywhere:

![image](https://user-images.githubusercontent.com/38782922/190378337-f27d85f7-92ef-4de1-98a2-ecb66cb0b8e6.png)

**Comment by ghost** [comment]
Hi.

> Thanks for the links! Sounds very exciting, but unfortunately, development seems to have ended over ten years ago?

I'm doing some concept research.

>  I doubt it will work with Squeak 5.3, but you can give it a try anyway ...

Anyway thanks for the information

**Comment by LinqLover** [comment]
You want to revive this or a similar project? Please keep me up to date 😃

**Comment by ghost** [comment]
Hi LinqLover. 

> You want to revive this or a similar project? Please keep me up to date 😃

Yes and no... It's in the backlog but no data defined. 😃

So... anyway... please, close this issue - all my doubts have been answered.
